/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.*;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static com.itextpdf.text.pdf.XfaXpathConstructor.XdpPackage.Pdf;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thevidu
 */
public class VBilling extends javax.swing.JFrame {
public int finalTotal=0;
    /**
     * Creates new form VBilling
     */
    public VBilling() {
        initComponents();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        lbl_date.setText(dFormat.format(date));
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        lbl_time.setText(dtf.format(now));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_contactno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_productId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_productName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_details = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_paidAmount = new javax.swing.JTextField();
        txt_returnAmount = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(220, 120));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1130, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/biling.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Billing.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, 56));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 27, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 55, -1, -1));

        lbl_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_date.setText("26 - 07 - 2022");
        getContentPane().add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 27, -1, -1));

        lbl_time.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_time.setText("24:30:20");
        getContentPane().add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 55, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Customer Details:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 159, -1, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 156, 138, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 159, -1, -1));

        txt_contactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactnoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 156, 131, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 159, -1, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 156, 199, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 159, -1, -1));

        txt_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 156, 117, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Product Details:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Product ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 269, -1, -1));

        txt_productId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productIdActionPerformed(evt);
            }
        });
        getContentPane().add(txt_productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 266, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Product Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 269, -1, -1));

        txt_productName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 266, 171, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Price(Rs)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 269, -1, -1));

        txt_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 266, 129, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Quantity");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 313, -1, -1));

        txt_quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 310, 55, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(727, 269, -1, -1));

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 266, 200, -1));

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 261, -1, -1));

        tbl_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_details);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 369, 630, 170));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Calculation Details:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 389, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Total (Rs)");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 417, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Paid Amount(Rs)");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 458, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Return Amount(Rs)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 502, -1, -1));

        txt_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 417, 129, -1));

        txt_paidAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_paidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paidAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txt_paidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 458, 129, -1));

        txt_returnAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_returnAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 499, 129, -1));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 99, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, -1, -1));

        btn_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 99, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 1134, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 344, 1134, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1134, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
      
     if(txt_name.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Name can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
    else{
       String name;
       ResultSet rs;
       name=txt_name.getText();
       
        CBilling obj=new CBilling();
        rs=obj.getSearchName(name);
        
        try
        {
         if (rs.next())
          {
          txt_name.setText(rs.getString(1));
          txt_contactno.setText(rs.getString(2));
          txt_email.setText(rs.getString(3));
          txt_address.setText(rs.getString(4));
          txt_name.setEditable(false);
          txt_contactno.setEditable(false);
          txt_email.setEditable(false);
          txt_address.setEditable(false);
          }
        
        else
        {
            txt_contactno.setText("");
            txt_email.setText("");
            txt_address.setText("");
        
        }
        }
       catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
     }
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactnoActionPerformed
       
     if(txt_contactno.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Contact no can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
     else{     
       String contactno;
       ResultSet rs;
       contactno=txt_contactno.getText();
       
        CBilling obj=new CBilling();
        rs=obj.getSearchcontact(contactno);
        
        try
        {
         if (rs.next())
          {
          txt_name.setText(rs.getString(1));
          txt_contactno.setText(rs.getString(2));
          txt_email.setText(rs.getString(3));
          txt_address.setText(rs.getString(4));
          txt_name.setEditable(false);
          txt_contactno.setEditable(false);
          txt_email.setEditable(false);
          txt_address.setEditable(false);
          }
        
        else
        {
            txt_name.setText("");
            txt_email.setText("");
            txt_address.setText("");
        
        }
        }
       catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
     }
    }//GEN-LAST:event_txt_contactnoActionPerformed

    private void txt_productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productIdActionPerformed
       
     if(txt_productId.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Product No can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
     else{
       String pID;
       ResultSet rs;
       pID=txt_productId.getText();
       
        CBilling obj=new CBilling();
        rs=obj.getSearchPID(pID);
        
        try
        {
         if (rs.next())
          {
          txt_productName.setText(rs.getString(2));
          txt_price.setText(rs.getString(3));
          txt_quantity.setText("1");
          txt_description.setText(rs.getString(4));

          txt_price.setEditable(false);
          txt_description.setEditable(false);
          
         
          }
        
        else
        {
            txt_productName.setText("");
            txt_price.setText("");
            txt_quantity.setText("");
            txt_description.setText("");
        
        }
        }
       catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
     }
    }//GEN-LAST:event_txt_productIdActionPerformed

    private void txt_productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productNameActionPerformed
      
    if(txt_productName.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Product Name can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
    else{  
        
       String pName;
       ResultSet rs;
       pName=txt_productName.getText();
       
        CBilling obj=new CBilling();
        rs=obj.getSearchPname(pName);
        
        try
        {
         if (rs.next())
          {
          txt_productId.setText(rs.getString(1));
          txt_productName.setText(rs.getString(2));
          txt_price.setText(rs.getString(3));
          txt_quantity.setText("1");
          txt_description.setText(rs.getString(4));
          
          txt_price.setEditable(false);
          txt_description.setEditable(false);
         
          }
        
        else
        {
            txt_productId.setText("");
            txt_price.setText("");
            txt_quantity.setText("");
            txt_description.setText("");
        
        }
        }
       catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
        
    }//GEN-LAST:event_txt_productNameActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
     
     if(txt_name.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Customer name can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
     else if(txt_contactno.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Contact no can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
      else if(txt_productId.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Product ID can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
       else if(txt_productName.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"Product Name can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE); 
        }
     else
     {
        try
        {

            int price=Integer.parseInt(txt_price.getText());
            int quantity=Integer.parseInt(txt_quantity.getText());
            int total=price*quantity;
            DefaultTableModel model=(DefaultTableModel)tbl_details.getModel();
            model.addRow(new Object[]{txt_productName.getText(),txt_description.getText(),price,quantity,total});
            finalTotal=finalTotal+total;
            String finalTotal=String.valueOf(this.finalTotal);
            txt_total.setText(finalTotal);
            txt_total.setEditable(false);

        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"Please fill the correct customer and product details","ERROR",JOptionPane.ERROR_MESSAGE);
        }
     }
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_paidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paidAmountActionPerformed
      
       if(!(txt_paidAmount.getText().matches("[0-9]+")))
       {
            JOptionPane.showMessageDialog(null,"Please enter number for Paid Amount","ERROR",JOptionPane.ERROR_MESSAGE);
         
       }
       else{
                try{
                String paidAmount=txt_paidAmount.getText();
                int z=Integer.parseInt(paidAmount);
                finalTotal=z-finalTotal;
                String finalTotal=String.valueOf(this.finalTotal);
                txt_returnAmount.setText(finalTotal);
                txt_returnAmount.setEditable(false);
                }
                catch(Exception e)
                {
                  JOptionPane.showMessageDialog(null, e.getMessage());  
                }
            }
    }//GEN-LAST:event_txt_paidAmountActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        setVisible(false);
        
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        setVisible(false);
        new VBilling().setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
     
        if(!(txt_paidAmount.getText().matches("[0-9]+")))
       {
            JOptionPane.showMessageDialog(null,"Please enter number for Paid Amount","ERROR",JOptionPane.ERROR_MESSAGE);
         
       }
       else{
        
                String name=txt_name.getText();
                String contactno=txt_contactno.getText();
                String email=txt_email.getText();
                String address=txt_address.getText();
                String path="D:\\";
                com.itextpdf.text.Document doc= new com.itextpdf.text.Document();

                try
                {

                    PdfWriter.getInstance(doc,new FileOutputStream(path+""+name+""+new Timestamp(System.currentTimeMillis()).getTime()+".pdf"));
                    doc.open();
                    Paragraph paragraph1=new Paragraph("                               TM Mobile Center - Colombo-08\n                                Contact Number:(+94)715828288\n\n");
                    doc.add(paragraph1);
                    Paragraph paragraph2=new Paragraph("Date & Time: "+lbl_date.getText()+ ""+lbl_time.getText()+"\nCustomer Details:-----\n\nName: "+name+"\nContact No: "+contactno+"\nEmail: "+email+"\nAddress: "+address+"\n\n");
                    doc.add(paragraph2);
                    PdfPTable tb1=new PdfPTable(5);
                    tb1.addCell("Name");
                    tb1.addCell("Description");
                    tb1.addCell("Price");
                    tb1.addCell("Quantity");
                    tb1.addCell("Sub Total");
                    for(int i=0;i<tbl_details.getRowCount();i++)
                    {
                        String n=tbl_details.getValueAt(i, 0).toString();
                        String d=tbl_details.getValueAt(i, 1).toString();
                        String p=tbl_details.getValueAt(i, 2).toString();
                        String q=tbl_details.getValueAt(i, 3).toString();
                        String s=tbl_details.getValueAt(i, 4).toString();
                        tb1.addCell(n);
                        tb1.addCell(d);
                        tb1.addCell(p);
                        tb1.addCell(q);
                        tb1.addCell(s);
                    }
                    doc.add(tb1);
                    Paragraph paragraph3=new Paragraph("\nTotal(Rs):  "+txt_total.getText()+"\nPaid Amount(Rs):  "+txt_paidAmount.getText()+"\nReturn Amount(Rs):  "+txt_returnAmount.getText()+"\n\nThanks You! and Please Come Again.\nTM Mobiles");
                    doc.add(paragraph3);
                    JOptionPane.showMessageDialog(null,"Bill Generated Successfully");
                    setVisible(true);
                    new VBilling().setVisible(true);



                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,e);

                }
                doc.close();
            }
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTable tbl_details;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contactno;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_paidAmount;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_productId;
    private javax.swing.JTextField txt_productName;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_returnAmount;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
