/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Thevidu
 */
public class VHome extends javax.swing.JFrame {

    /**
     * Creates new form VHome
     */
    public VHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_addcustomer = new javax.swing.JButton();
        btn_updatecustomer = new javax.swing.JButton();
        btn_customerdetails = new javax.swing.JButton();
        btn_deletecustomer = new javax.swing.JButton();
        btn_newproduct = new javax.swing.JButton();
        btn_updateproduct = new javax.swing.JButton();
        btn_productdetails = new javax.swing.JButton();
        btn_deleteproduct = new javax.swing.JButton();
        btn_biling = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_addcustomer.setBackground(new java.awt.Color(179, 232, 229));
        btn_addcustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_addcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new customer.png"))); // NOI18N
        btn_addcustomer.setText("New Customer");
        btn_addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 210, 64));

        btn_updatecustomer.setBackground(new java.awt.Color(179, 232, 229));
        btn_updatecustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_updatecustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer update.png"))); // NOI18N
        btn_updatecustomer.setText("Update Customer");
        btn_updatecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatecustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updatecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 210, 64));

        btn_customerdetails.setBackground(new java.awt.Color(179, 232, 229));
        btn_customerdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_customerdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer details.png"))); // NOI18N
        btn_customerdetails.setText("Customer Details");
        btn_customerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_customerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 210, 64));

        btn_deletecustomer.setBackground(new java.awt.Color(179, 232, 229));
        btn_deletecustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_deletecustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete customer.png"))); // NOI18N
        btn_deletecustomer.setText("Delete Customer");
        btn_deletecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deletecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 257, 210, 64));

        btn_newproduct.setBackground(new java.awt.Color(179, 232, 229));
        btn_newproduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_newproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add product.png"))); // NOI18N
        btn_newproduct.setText("New Product");
        btn_newproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newproductActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 339, 210, 64));

        btn_updateproduct.setBackground(new java.awt.Color(179, 232, 229));
        btn_updateproduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_updateproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update prodruct.png"))); // NOI18N
        btn_updateproduct.setText("Update Product");
        btn_updateproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateproductActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updateproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, 210, 64));

        btn_productdetails.setBackground(new java.awt.Color(179, 232, 229));
        btn_productdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_productdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product details.png"))); // NOI18N
        btn_productdetails.setText("Product Details");
        btn_productdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_productdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 503, 210, 64));

        btn_deleteproduct.setBackground(new java.awt.Color(179, 232, 229));
        btn_deleteproduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_deleteproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete product.png"))); // NOI18N
        btn_deleteproduct.setText("Delete Product");
        btn_deleteproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteproductActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deleteproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 585, 210, 64));

        btn_biling.setBackground(new java.awt.Color(179, 232, 229));
        btn_biling.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_biling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/biling.png"))); // NOI18N
        btn_biling.setText("Biling");
        btn_biling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_biling, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 667, 210, 64));

        btn_logout.setBackground(new java.awt.Color(179, 232, 229));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 210, 64));

        btn_close.setBackground(new java.awt.Color(179, 232, 229));
        btn_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close home.png"))); // NOI18N
        btn_close.setText("Close");
        btn_close.setPreferredSize(new java.awt.Dimension(145, 73));
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1138, 12, 210, 63));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background home page.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1540, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
       int a=JOptionPane.showConfirmDialog(null,"Do you want to Logout","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           setVisible(false);
           new VLogin().setVisible(true);
       }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_addcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcustomerActionPerformed
        new VNewCustomer().setVisible(true);
    }//GEN-LAST:event_btn_addcustomerActionPerformed
   
   
    private void btn_updatecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatecustomerActionPerformed
        new VUpdateCustomer().setVisible(true);
    }//GEN-LAST:event_btn_updatecustomerActionPerformed

    private void btn_customerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerdetailsActionPerformed
        new VCustomerDetails().setVisible(true);
    }//GEN-LAST:event_btn_customerdetailsActionPerformed

    private void btn_deletecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletecustomerActionPerformed
        new VDeleteCustomer().setVisible(true);
    }//GEN-LAST:event_btn_deletecustomerActionPerformed

    private void btn_newproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newproductActionPerformed
         new VNewProduct().setVisible(true);
    }//GEN-LAST:event_btn_newproductActionPerformed

    private void btn_updateproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateproductActionPerformed
         new VUpdateProduct().setVisible(true);
    }//GEN-LAST:event_btn_updateproductActionPerformed

    private void btn_productdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productdetailsActionPerformed
        new VProductDeatails().setVisible(true);
    }//GEN-LAST:event_btn_productdetailsActionPerformed

    private void btn_deleteproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteproductActionPerformed
         new VDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btn_deleteproductActionPerformed

    private void btn_bilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilingActionPerformed
         new VBilling().setVisible(true);
    }//GEN-LAST:event_btn_bilingActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Exit","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
          System.exit(0);
       }
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcustomer;
    private javax.swing.JButton btn_biling;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_customerdetails;
    private javax.swing.JButton btn_deletecustomer;
    private javax.swing.JButton btn_deleteproduct;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_newproduct;
    private javax.swing.JButton btn_productdetails;
    private javax.swing.JButton btn_updatecustomer;
    private javax.swing.JButton btn_updateproduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
