/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Thevidu
 */
public class VRegistration extends javax.swing.JFrame {

    /**
     * Creates new form VRegistration
     */
    public VRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_workerID = new javax.swing.JTextField();
        txt_workername = new javax.swing.JTextField();
        txt_NIC = new javax.swing.JTextField();
        txt_contactno = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_save = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        pwd_password = new javax.swing.JPasswordField();
        chb_show = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Registration.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 11, 267, 55));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Register 1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 0, -1, 73));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Worker ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Worker Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 151, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NIC No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 192, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Contact No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 233, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("User Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 274, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 315, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 356, -1, -1));

        txt_workerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_workerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 107, 250, -1));

        txt_workername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_workername, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 148, 250, -1));

        txt_NIC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 189, 250, -1));

        txt_contactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 230, 250, -1));

        txt_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 271, 250, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 353, 250, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 403, 580, 10));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 108, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 108, -1));

        btn_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancel.png"))); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 108, -1));

        pwd_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(pwd_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 312, 250, -1));

        chb_show.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chb_show.setText("Show");
        chb_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_showActionPerformed(evt);
            }
        });
        getContentPane().add(chb_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register background.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        setVisible(false);
        new VRegistration().setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String workerID,workerName,NIC,contactNo,userName,password,email;
       
        
        workerID=txt_workerID.getText();
        workerName=txt_workername.getText();
        NIC=txt_NIC.getText();
        contactNo=txt_contactno.getText();
        userName=txt_username.getText();
        password=pwd_password.getText();
        email=txt_email.getText();
       
        
         if(txt_workerID.getText().equals(""))
        {
               JOptionPane.showMessageDialog(null,"Worker ID Can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
         else if(!(txt_workerID.getText().matches("[0-9]+")))
        {
            JOptionPane.showMessageDialog(null,"Please enter numeric values for Worker ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
         
        else if(txt_workername.getText().equals(""))
        {
              JOptionPane.showMessageDialog(null,"Name Can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_NIC.getText().isEmpty())
        {  
            JOptionPane.showMessageDialog(null,"NIC can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_NIC.getText().length()<10 || txt_NIC.getText().length()>12 || txt_NIC.getText().length()==11)
        {  
            JOptionPane.showMessageDialog(null,"Please enter correct NIC","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        else if(txt_contactno.getText().isEmpty()||txt_contactno.getText().length()!=10)
        {  
            JOptionPane.showMessageDialog(null,"Enter correct Contact No","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(!(txt_contactno.getText().matches("[0-9]+"))){
            JOptionPane.showMessageDialog(null,"Please enter numeric values for Contact no","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_username.getText().equals(""))
        {
               JOptionPane.showMessageDialog(null,"Username Can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(pwd_password.getText().equals(""))
        {
               JOptionPane.showMessageDialog(null,"Password Can't be Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(!(txt_email.getText().matches("^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{3}$"))){
             JOptionPane.showMessageDialog(null,"Enter correct Email","ERROR",JOptionPane.ERROR_MESSAGE);              
        }
        else
         {
        
            CRegistration obj=new  CRegistration();
           obj.getNewWorker(workerID,workerName,NIC,contactNo,userName,password,email);

            setVisible(false);
           new VRegistration().setVisible(true);
         }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void chb_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_showActionPerformed
         if(chb_show.isSelected())
       {
           pwd_password.setEchoChar((char)0);
       }
       else
           pwd_password.setEchoChar('*');
    }//GEN-LAST:event_chb_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox chb_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pwd_password;
    private javax.swing.JTextField txt_NIC;
    private javax.swing.JTextField txt_contactno;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_workerID;
    private javax.swing.JTextField txt_workername;
    // End of variables declaration//GEN-END:variables
}
